name: Package Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Install WiX Toolset
      run: |
        Invoke-WebRequest -Uri 'https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip' -OutFile 'wix314-binaries.zip'
        Expand-Archive -Path 'wix314-binaries.zip' -DestinationPath 'C:\Program Files\WiX Toolset v3.14'
        # Add WiX Toolset to PATH
        $env:Path += ';C:\Program Files\WiX Toolset v3.14'
    - name: Build
      run: npm run make
    - name: Upload Artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: |
          out/make/squirrel.windows/x64/RELEASES
          out/make/squirrel.windows/x64/kbs_electron-${{ github.event.release.tag_name }}-full.nupkg
          out/make/squirrel.windows/x64/Keyboard Sounds-${{ github.event.release.tag_name }} Setup.exe
          out/make/wix/x64/Keyboard Sounds.msi
          out/make/wix/x64/Keyboard Sounds.wixobj
          out/make/wix/x64/Keyboard Sounds.wixpdb
          out/make/wix/x64/Keyboard Sounds.wxs
